import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../components/MenuCard'
import { useEffect ,useState} from 'react';
import Description from '../components/Description';
import ImageCard from '../components/ImageCard';
import { style } from '@mui/system';

export default function Home(props) {
  const [chosenPlanet,setChosenPlanet]=useState("Earth")

 const setPlanet =(option)=>{
  setChosenPlanet(option)
 }

//  useEffect((option)=>{
// setPlanet(option);
// },[])


  return (
    <div className={styles.container}>

      <Head>
        <title>planets facts</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        

      <main className={styles.main}>
          <Menu  selectedOption={chosenPlanet} ChosenClickHandler ={setPlanet} />
         
          <div className = {styles.planetComponent}>
          {chosenPlanet && <ImageCard className={styles.planetImage} planet={chosenPlanet}/>}
          {chosenPlanet && <Description className={styles.desc} planetClicked={chosenPlanet} />}
          </div>
        
         
          <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        <a href="https://www.wikipedia.org/">
          <span>
            <p>source wikipedia </p>
          </span>
        </a>
      </footer>
        
      </main>
         
     

      
    </div>
  )
}
