import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Menu from '../components/MenuCard'
import { useEffect ,useState} from 'react';
import Description from '../components/Description';

export default function Home(props) {

  const [chosenPlanet,setChosenPlanet]=useState("")
  const name={props};
  const API_URL = `https://api.api-ninjas.com/v1/planets?name= ${name}`

 async function searchPlanet(){
  const options={
     headers:{
      'X-Api-Key':'UYrtxdj/yHEsGj8u8hK1qg==MJBvJ33RumjZ4EJU',
    
    }

  }
  
  const response =await fetch(`https://api.api-ninjas.com/v1/planets?name=${name}`,options);
  const data = response.json();
  console.log(data);
 }

 const [planets,setPalnets] = useState([])
 useEffect(()=>{
  searchPlanet();
 },[])

 const setPlanet =(option)=>{
  setChosenPlanet(option)
 }


  return (
    <div className={styles.container}>
      {chosenPlanet}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Menu option = {chosenPlanet} ChosenClickHandler ={setPlanet}/>
      <h1>{chosenPlanet}</h1>
      <Description planetClicked={chosenPlanet}/>

     
         
      </main>
         
      {/* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}

      
    </div>
  )
}
